In [ ]:
#Feature Engineering (Encoding and Scaling)

In [ ]:
# LabelEncoder converts the text/categorical columns into numerical data

from sklearn.preprocessing import LabelEncoder
import pandas as pd

#creating data frames
data = pd.DataFrame({'Education':['High School','Bachelor','Master','PhD','Bachelor','High School']})

In [10]:
data

     Education
0  High School
1     Bachelor
2       Master
3          PhD
4     Bachelor
5  High School

In [11]:
le = LabelEncoder()
le.fit_transform(data['Education'])

array([1, 0, 2, 3, 0, 1])

In [12]:
print('classes:',le.classes_)

classes: ['Bachelor' 'High School' 'Master' 'PhD']

In [15]:
print(le.inverse_transform([0,1,2,3]))

['Bachelor' 'High School' 'Master' 'PhD']

In [21]:
# One Hot Encoding
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
#Animal Type (Nominal - no order)
data =pd.DataFrame({'Animal':['Cat','Dog','Fish','Dog','Cat']})
data

  Animal
0    Cat
1    Dog
2   Fish
3    Dog
4    Cat

In [27]:
#Method1-pandas get_dummies()
encoded = pd.get_dummies(data, columns = ['Animal'])
print(encoded)

   Animal_Cat  Animal_Dog  Animal_Fish
0        True       False        False
1       False        True        False
2       False       False         True
3       False        True        False
4        True       False        False

In [29]:
#Method1-pandas get_dummies() dropping first column
encoded = pd.get_dummies(data, columns = ['Animal'],drop_first=True)
print(encoded)

   Animal_Dog  Animal_Fish
0       False        False
1        True        False
2       False         True
3        True        False
4       False        False

In [46]:
ohe =OneHotEncoder(drop="first",sparse_output= False)
result = ohe.fit_transform(data [["Animal"]])
col_name = ohe.get_feature_names_out(["Animal"])
encoded_df = pd.DataFrame(result, columns=col_name)
encoded_df

   Animal_Dog  Animal_Fish
0         0.0          0.0
1         1.0          0.0
2         0.0          1.0
3         1.0          0.0
4         0.0          0.0

In [47]:
col_name
encoded_df

   Animal_Dog  Animal_Fish
0         0.0          0.0
1         1.0          0.0
2         0.0          1.0
3         1.0          0.0
4         0.0          0.0

In [53]:
#ordinal encoding is like label encoding but define order

from sklearn.preprocessing import OrdinalEncoder
import pandas as pd
data = pd.DataFrame({'Size':['Small','Large','Medium','XL','Small','Medium'],
                     'Grade':['Poor','Good','Average','Excellent','Good','Average']})
oe = OrdinalEncoder(categories =[
    ["Small","Medium","Large","XL"],
    ["Poor","Average","Good","Excellent"]])
data[["size_enc","grade_enc"]] = oe.fit_transform(data[['Size','Grade']])
print(data)

     Size      Grade  size_enc  grade_enc
0   Small       Poor       0.0        0.0
1   Large       Good       2.0        2.0
2  Medium    Average       1.0        1.0
3      XL  Excellent       3.0        3.0
4   Small       Good       0.0        2.0
5  Medium    Average       1.0        1.0

In [2]:
# Scaling method MInMaxScaler use in Deep Learning (Normalization)

from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np
data = pd.DataFrame({'Age':[25,30,35,40,45,50],
                      'Salary':[30000,45000,60000,75000,90000,120000]})
data
scaler = MinMaxScaler(feature_range= (0,1))
data_scaled = scaler.fit_transform(data)
df_scaled = pd.DataFrame( data_scaled,columns =['Age_scaled','Salary_scaled'])
print(df_scaled)

   Age_scaled  Salary_scaled
0         0.0       0.000000
1         0.2       0.166667
2         0.4       0.333333
3         0.6       0.500000
4         0.8       0.666667
5         1.0       1.000000

In [3]:
data

   Age  Salary
0   25   30000
1   30   45000
2   35   60000
3   40   75000
4   45   90000
5   50  120000

In [7]:
# Standard Scaling also called standardization
#Data follows normal distribution or bell shaped curve
# mean = 0 and std deviation = 1

from sklearn.preprocessing import StandardScaler

data = pd.DataFrame ({
    "Height": [150,160,165,170,175,180,190],
    "Weight": [50,60,65,70,75,80,95]
})
data
# scaler = StandardScaler()
# data_scaled = scaler.fit_transform(data)
    
# data_scaled

   Height  Weight
0     150      50
1     160      60
2     165      65
3     170      70
4     175      75
5     180      80
6     190      95

In [8]:
from sklearn.preprocessing import StandardScaler

data = pd.DataFrame ({
    "Height": [150,160,165,170,175,180,190],
    "Weight": [50,60,65,70,75,80,95]
})

scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

data_scaled

array([[-1.63299316, -1.53699693],
       [-0.81649658, -0.79499841],
       [-0.40824829, -0.42399915],
       [ 0.        , -0.05299989],
       [ 0.40824829,  0.31799936],
       [ 0.81649658,  0.68899862],
       [ 1.63299316,  1.8019964 ]])

In [9]:
from sklearn.preprocessing import StandardScaler

data = pd.DataFrame ({
    "Height": [150,160,165,170,175,180,190],
    "Weight": [50,60,65,70,75,80,95]
})

scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)
data_scaled = pd.DataFrame(data_scaled, columns = ["Height_std", "Weight_std"])
data_scaled

   Height_std  Weight_std
0   -1.632993   -1.536997
1   -0.816497   -0.794998
2   -0.408248   -0.423999
3    0.000000   -0.053000
4    0.408248    0.317999
5    0.816497    0.688999
6    1.632993    1.801996